project_id = "uopacrm"

[api]
enabled = true
port = 54321
schemas = ["public", "graphql_public"]
extra_search_path = ["public", "extensions"]
max_rows = 1000

[db]
port = 54322
shadow_port = 54323
major_version = 15

[db.pooler]
enabled = true
port = 54324
pool_mode = "transaction"
default_pool_size = 20
max_pool_size = 20

[realtime]
enabled = true
port = 54325

[studio]
enabled = true
port = 54326

[inbucket]
enabled = true
port = 54327

[edge_runtime]
enabled = true
port = 54328
inspector_port = 54329

[analytics]
enabled = true
port = 54330

[auth]
enabled = true
site_url = "http://localhost:3000"
additional_redirect_urls = ["http://localhost:3000/**"]
jwt_expiry = 3600
enable_signup = true

[auth.email]
enable_signup = true

[storage]
enabled = true

[storage.image_transformation]
enabled = true
