project_id = "btoyclznuuwvxbsacemw"

[functions.master-proxy]
verify_jwt = false

[functions.master-analytics]
verify_jwt = false

[functions.master-tenants]
verify_jwt = false

[functions.master-users]
verify_jwt = false

[functions.master-branding]
verify_jwt = false

[functions.master-subscriptions]
verify_jwt = false

[functions.master-settings]
verify_jwt = false

[functions.create-subscription]
verify_jwt = false

[functions.impersonate]
verify_jwt = false

[functions.invite-links]
verify_jwt = false

[functions.onboarding]
verify_jwt = false

[functions.feature-flags]
verify_jwt = false

[functions.broadcasts]
verify_jwt = false

[functions.unit-economics]
verify_jwt = false

[functions.master-templates-proxy]
verify_jwt = false

[functions.master-invite]
verify_jwt = false

[functions.stripe-webhook]
verify_jwt = false

[functions.customer-portal]
verify_jwt = false

[functions.create-tenant-checkout]
verify_jwt = false

[functions.verify-domains]
verify_jwt = false

[functions.check-limits]
verify_jwt = false

[functions.master-tenant-features]
verify_jwt = false

[functions.master-user-limits]
verify_jwt = false

[functions.master-billing]
verify_jwt = false

[functions.master-usage]
verify_jwt = false

[functions.master-ai-insights]
verify_jwt = false

[functions.master-ai-diagnostics]
verify_jwt = false

[functions.log-api-usage]
verify_jwt = false

[functions.sync-tenant-to-crm]
verify_jwt = false
