project_id = "btoyclznuuwvxbsacemw"

[functions.master-proxy]
verify_jwt = false

[functions.master-analytics]
verify_jwt = false

[functions.master-tenants]
verify_jwt = false

[functions.master-users]
verify_jwt = false

[functions.master-branding]
verify_jwt = false

[functions.master-subscriptions]
verify_jwt = false

[functions.create-subscription]
verify_jwt = false

[functions.impersonate]
verify_jwt = false

[functions.invite-links]
verify_jwt = false

[functions.onboarding]
verify_jwt = false

[functions.feature-flags]
verify_jwt = false

[functions.broadcasts]
verify_jwt = false

[functions.unit-economics]
verify_jwt = false

[functions.master-templates-proxy]
verify_jwt = false

[functions.master-invite]
verify_jwt = false
