// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://btoyclznuuwvxbsacemw.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImJ0b3ljbHpudXV3dnhic2FjZW13Iiwicm9sZSI6ImFub24iLCJpYXQiOjE3Njc2NTIyNDEsImV4cCI6MjA4MzIyODI0MX0.gqhEFgwh-VFtsZQwqnXwv6Suncj87qaNHF0u6qXCMu4";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});